FROM docker.io/nadavker/fedora-43-base:latest

WORKDIR "/home"
RUN git clone https://github.com/NadavKeren/caffeine.git
RUN git clone https://github.com/NadavKeren/NSDI-Pipeline-Cache.git /home/artifact
WORKDIR "/home/caffeine"
RUN git checkout NSDI

RUN pip install xxhash

# FIRST COMPILATION
RUN ./gradlew compileJava

# Setting the simulation tools for the experiments
WORKDIR "/home/artifact"
RUN echo '{ "caffeine_root" : "/home/caffeine/", "resources" : "/home/traces/", "output" : "" , "results": "/home/results" }' > experiments/conf.json

ENTRYPOINT ["/bin/bash"]

CMD ["--login"]
